version: '3.7'

services:
    db:
        container_name: db
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - DATABASE_USER=dev_user
            - DATABASE_PASSWORD=dev_password
            - DATABASE_NAME=dev
            - DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
            - DATABASE_HOST=localhost
            - DATABASE_PORT=5432

    web:
        container_name: web
        build:
            context: ./web
            dockerfile: Dockerfile
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - 8000:8000
            - 3000:3000
            - 35729:35729
        env_file:
            - ./.env
        stdin_open: true
        depends_on:
            - db

volumes:
    postgres_data:
