# Generated by Django 3.2 on 2021-05-06 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountUID', models.AutoField(primary_key=True, serialize=False, verbose_name='Account UID')),
                ('accountID', models.CharField(max_length=25, verbose_name='Account ID')),
                ('currentBalance', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Current Balance')),
                ('name', models.CharField(max_length=50, verbose_name='Account Name')),
                ('type', models.CharField(max_length=25, verbose_name='Account Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionUID', models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction UID')),
                ('transactionID', models.CharField(max_length=50, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Transaction Amount')),
                ('date', models.DateField(verbose_name='Transaction Date')),
                ('categoryID', models.CharField(max_length=50, verbose_name='Transaction Category ID')),
                ('merchantName', models.CharField(max_length=50, verbose_name='Merchant Name')),
                ('merchantLocation', models.CharField(max_length=50, verbose_name='Merchant Location')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backend.account')),
            ],
        ),
        migrations.CreateModel(
            name='PlaidToken',
            fields=[
                ('accessTokenUID', models.AutoField(primary_key=True, serialize=False, verbose_name='Access Token UID')),
                ('accessToken', models.CharField(default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plaidToken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
